### ISSUE TITLE
support linux

### ISSUE THREAD

**Issue by razvanpaul-mielcioiu** [SkylineCommunications/Skyline.DataMiner.CICD.Tools.DataMinerDeploy#10]
This is a great tool!
Are there any plans to support Linux?

**Comment by janstaelensskyline** [comment]
Hi there, thanks for the feedback!

Currently, if you use the tool to deploy from the catalog, it supports Linux. So, if you have an agent connected to dataminer.services and deploy with 'from-catalog', this tool has full Linux support.

The recently added deployment option 'from-artifact,' directly to an agent, doesn't work on Linux. I tried rather hard to get that to work; I managed to get it running on this .NET solution instead of .NETFramework, which was a challenge. That took some effort because the assemblies from DataMiner that we use to connect directly to an agent have never really been converted to work on .NET Standard and Linux.

The problem is that currently, SLNetTypes.dll uses several unmanaged win32 assemblies to talk directly to the Windows OS for several calls that happen during the upload of a .dmprotocol. Unfortunately, this means that if we want to support this tool to deploy from Linux, we'd need to rework those assemblies, which are currently at the core of our DataMiner code.

So for now, this isn't on our roadmap (this year) due to the sheer amount of work involved, the impact on DataMiner it would cause, and due to the current viable way of deploying from the catalog.

But for anyone reading this, don't hesitate to provide additional feedback or remarks as well. If the interest is really high, we can dig deeper and maybe brainstorm other alternatives.
